package together
// Package together provides Together AI provider implementation
package together




























































}	}		"Qwen/Qwen2.5-Coder-32B-Instruct",		"deepseek-ai/DeepSeek-Coder-V2-Instruct",		// Code models		"Qwen/Qwen2.5-7B-Instruct-Turbo",		"Qwen/Qwen2.5-72B-Instruct-Turbo",		// Qwen		"mistralai/Mixtral-8x22B-Instruct-v0.1",		"mistralai/Mixtral-8x7B-Instruct-v0.1",		// Mixtral		"meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",		"meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",		"meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",		"meta-llama/Llama-3.3-70B-Instruct-Turbo",		// Llama 3 models	return []string{func AvailableModels() []string {// AvailableModels returns commonly available Together AI models}	return p.c.Chat(ctx, req)func (p *Together) Chat(ctx context.Context, req provider.ChatRequest) (provider.ChatResponse, error) {}	return p.c.ListModels(ctx)func (p *Together) ListModels(ctx context.Context) ([]provider.Model, error) {}	return p.c.Health(ctx)func (p *Together) Health(ctx context.Context) error {func (p *Together) Endpoint() string { return defaultBaseURL }func (p *Together) Kind() string     { return "remote" }func (p *Together) Name() string     { return "together" }}	}		c: openai_compat.New(defaultBaseURL, apiKey, nil),	return &Together{func New(apiKey string) *Together {// New creates a new Together AI provider}	c *openai_compat.Clienttype Together struct {// Together AI offers various open-source models// Together implements the Together AI provider)	defaultBaseURL = "https://api.together.xyz/v1"const ()	"devorch/internal/provider/openai_compat"	"devorch/internal/provider"	"context"import (