-- Step 14: router_policy를 scope-aware로 확장
-- NOTE: scope_type and scope_id columns have been moved to 0015_router_policy.sql
-- to ensure idempotent migrations. This file is kept as a no-op for existing DBs.
--
-- Original commands:
-- ALTER TABLE router_policy ADD COLUMN scope_type TEXT NOT NULL DEFAULT 'global';
-- ALTER TABLE router_policy ADD COLUMN scope_id   TEXT NOT NULL DEFAULT '*';
-- DROP INDEX IF EXISTS idx_router_policy_key;
-- CREATE INDEX IF NOT EXISTS idx_router_policy_scope_key ON router_policy(...);
--
-- No-op: SELECT 1;
